version: '3.8'
services:
  frontend-app:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      - BACKEND_API_URL=${BACKEND_API_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - api

  api:
    build: ./backend/api
    ports:
      - "8000:8000"
    environment:
      - CHROMA_HOSTNAME=${CHROMA_HOSTNAME}
      - CHROMA_PORT=${CHROMA_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma
    volumes:
      - ./backend/chroma/:/chroma/chroma/

# docker-compose build
# docker-compose up
# docker-compose up --build