version: '3.8'
services:
  frontend-app:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - api

  api:
    build: ./backend/api
    ports:
      - "8000:8000"
    env_file:
      - ./backend/api/.env
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma
    volumes:
      - ./backend/chroma/:/chroma/chroma/

# docker-compose build
# docker-compose up
# docker-compose up --build